# Generated by Django 3.0.2 on 2020-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, null=True)),
                ('realname', models.CharField(max_length=200, null=True)),
                ('origin_desription', models.CharField(max_length=1000)),
                ('superpowers', models.CharField(max_length=1000, null=True)),
                ('catch_phrase', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
